title: Memohat's Emporium
author: Mehmet Hatip
email: mbhatip@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Mehmet's website, where he will post stuff

# social links
twitter_username: mbhatip # DO NOT include the @ character, or else the build will fail!
github_username:  mbhatip # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
